name: Deployment
on:
  push:
    branches: [master]
    paths:
      - "src/**/*.html"
      - "dist/**/*.html"
      - "src/**/*.css"
      - "dist/**/*.css"
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install --only=prod
      - name: Update base href
        run: node scripts/dep.js
      - name: Minify HTML
        run: npm run html-minify
      - name: Create CSS directory
        run: mkdir -p dist/assets/css/
      - name: Minify CSS
        run: npm run css-minify
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Dylan Sealy"
          author_email: 66305635+DylanSealy@users.noreply.github.com
          message: "GitHub action: Deployment"
          push: true
