name: Development
on:
  push:
    branches: [ontwikkeling]
    paths:
      - "dist/**/*.html"
      - "src/**/*.html"
jobs:
  Change-base-href:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install --only=prod
      - name: Update base href
        run: node scripts/dev.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Dylan Sealy"
          author_email: 66305635+DylanSealy@users.noreply.github.com
          message: "GitHub action: Development"
          push: true
